version: "3.4"

services:
  tracker:
    build: .
    networks:
      - tracker_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.3
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=my_db
      # change this locally and update config.ini accordingly
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - tracker_network
    volumes:
      - ./db_data:/var/lib/mysql
    expose:
      - "3306"

networks:
  tracker_network:
    driver: bridge
